wordpress:
        image: wordpress
        links:
                - wordpressdb:mysql
        ports:
                - 8082:80

wordpressdb:
        image: mariadb
        environment:
                MYSQL_ROOT_PASSWORD: edureka

       
phpmyadmin:
        image: corbinu/docker-phpmyadmin
        links: 
                - wordpressdb:mysql
        ports:
                - 8181:80
        environment:
                MYSQL_USERNAME: root
                MYSQL_ROOT_PASSWORD: edureka                
